version: '3'

services:
  sale-platform-gateway-api:
    build:
      context: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5000
    ports:
      - "5000:5000"