name: Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.100'
    
    - name: Build
      run: dotnet build MyProject.csproj
      
    - name: Test
      run: dotnet test MyProject.Test.csproj
